In [6]:
import numpy as np
import matplotlib.pyplot as plt
from show_politope import *
from scipy.optimize import linprog
from scipy.spatial import HalfspaceIntersection, ConvexHull
from pycvxset import Polytope, Ellipsoid, spread_points_on_a_unit_sphere
import os
import argparse
from tqdm import tqdm
import math

m = 4
r = 2

base_path="./data/"
path = base_path + "m_" + str(m) + "_r_" + str(r) + "/"

exact_politopes_x_normalized = np.load(path + "exact_politopes_x_normalized.npy", allow_pickle=True)
exact_politopes_x = np.load(path + "exact_politopes_x.npy", allow_pickle=True)
exact_politopes_y = np.load(path + "exact_politopes_y.npy", allow_pickle=True)

In [13]:
print("exact_politopes_x_normalized[0]", exact_politopes_x_normalized[0])
print("exact_politopes_x[0]", exact_politopes_x[0])
print("exact_politopes_y[0]", exact_politopes_y[0])

A = np.array([[0.09650174844546099, 0.0027096172812189653],
              [-0.03940585249072831, 0.12525436930706524],
              [-0.04658126296750346, -0.080299591465464],
              [0.09619576003074763,  0.0790462760056176]
              ])
b = np.array([0.4414746715193314, 0.571488057593367, 0.34262141823364284, 0.5571632561784159])
print("A", A)
print("b", b)
polytope = Polytope(A=A, b=b)
volume = polytope.volume()
print("volume", volume)


exact_politopes_x_normalized[0] [[0.09650174844546099 0.0027096172812189653 0.4414746715193314]
 [-0.03940585249072831 0.12525436930706524 0.571488057593367]
 [-0.04658126296750346 -0.080299591465464 0.34262141823364284]
 [0.09619576003074763 0.0790462760056176 0.5571632561784159]]
exact_politopes_x[0] [[7.626143454753798 0.21413011087290545 34.887960382909405]
 [-3.114085380753495 9.898346963218357 45.16239322180499]
 [-3.681129092645996 -6.345752421468751 27.075986997247583]
 [7.6019624260813945 6.24670796222508 44.03036201707488]]
exact_politopes_y[0] 87.30192562222979
A [[ 0.09650175  0.00270962]
 [-0.03940585  0.12525437]
 [-0.04658126 -0.08029959]
 [ 0.09619576  0.07904628]]
b [0.44147467 0.57148806 0.34262142 0.55716326]
volume 87.3019256222298


In [16]:
#Normalize all data

base_path = "./data/"

m_array = [3, 4, 5]
r_array = [2, 3, 4]


m_array = [5]
r_array = [3, 4]


for m in m_array:
    for r in r_array:
        if m > r:
        
            path = base_path + "m_" + str(m) + "_r_" + str(r) + "/"
            exact_politopes_x = np.load(path + "exact_politopes_x.npy", allow_pickle=True)
            
            exact_politopes_x_normalized = np.zeros((len(exact_politopes_x), m, r+1))
            
            for i in range(len(exact_politopes_x_normalized)):
                exact_politopes_x_normalized[i] = exact_politopes_x[i] / np.linalg.norm(exact_politopes_x[i])

            np.save(path + "exact_politopes_x_normalized.npy", exact_politopes_x_normalized)


In [19]:
m = 5
r = 3

base_path="./data/"
path = base_path + "m_" + str(m) + "_r_" + str(r) + "/"

exact_politopes_x_normalized = np.load(path + "exact_politopes_x_normalized.npy", allow_pickle=True)
exact_politopes_x = np.load(path + "exact_politopes_x.npy", allow_pickle=True)
exact_politopes_y = np.load(path + "exact_politopes_y.npy", allow_pickle=True)

print(exact_politopes_x_normalized[0])
print(exact_politopes_x[0])
print(exact_politopes_y[0])

[[-0.08232348  0.03001744 -0.14401361 -0.01937042]
 [-0.19615903 -0.0266684   0.10577082  0.2431476 ]
 [ 0.04605125 -0.07093967  0.08763539  0.48579074]
 [-0.00624683  0.20149975  0.11135167  0.47986093]
 [ 0.13337732 -0.09699841 -0.14026484  0.52981488]]
[[-4.081463059811734 1.4882153760563437 -7.13995831471439
  -0.9603535432967778]
 [-9.725242827670428 -1.3221755130013708 5.243943437184393
  12.054858706016969]
 [2.2831454748577595 -3.5170724838524787 4.344818785909865
  24.08470744213026]
 [-0.3097073378025339 9.990027045140536 5.520633048895611
  23.790717317790758]
 [6.612628825435181 -4.8090218772244375 -6.954100743023721
  26.267352273741707]]
95.51339992358257
